/*
 * Mesa 3-D graphics library
 *
 * Copyright (C) 2012 LunarG Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Authors:
 *    Chia-I Wu <olv@lunarg.com>
 */

#ifndef I965_STATE_H
#define I965_STATE_H

#include "pipe/p_compiler.h"

/**
 * States that we track.
 *
 * XXX Do we want to count each sampler or vertex buffer as a state?  If that
 * is the case, there are simply not enough bits.
 */
enum i965_state {
   I965_STATE_BLEND,
   I965_STATE_FRAGMENT_SAMPLERS,
   I965_STATE_VERTEX_SAMPLERS,
   I965_STATE_GEOMETRY_SAMPLERS,
   I965_STATE_COMPUTE_SAMPLERS,
   I965_STATE_RASTERIZER,
   I965_STATE_DEPTH_STENCIL_ALPHA,
   I965_STATE_FS,
   I965_STATE_VS,
   I965_STATE_GS,
   I965_STATE_VERTEX_ELEMENTS,
   I965_STATE_BLEND_COLOR,
   I965_STATE_STENCIL_REF,
   I965_STATE_SAMPLE_MASK,
   I965_STATE_CLIP,
   I965_STATE_CONSTANT_BUFFER,
   I965_STATE_FRAMEBUFFER,
   I965_STATE_POLY_STIPPLE,
   I965_STATE_SCISSOR,
   I965_STATE_VIEWPORT,
   I965_STATE_FRAGMENT_SAMPLER_VIEWS,
   I965_STATE_VERTEX_SAMPLER_VIEWS,
   I965_STATE_GEOMETRY_SAMPLER_VIEWS,
   I965_STATE_COMPUTE_SAMPLER_VIEWS,
   I965_STATE_SHADER_RESOURCES,
   I965_STATE_VERTEX_BUFFERS,
   I965_STATE_INDEX_BUFFER,
   I965_STATE_STREAM_OUTPUT_TARGETS,
   I965_STATE_COMPUTE,
   I965_STATE_COMPUTE_RESOURCES,
   I965_STATE_GLOBAL_BINDING,

   I965_STATE_COUNT,
};

/**
 * Dirty flags of the states.
 */
enum i965_dirty_flags {
   I965_DIRTY_BLEND                    = 1 << I965_STATE_BLEND,
   I965_DIRTY_FRAGMENT_SAMPLERS        = 1 << I965_STATE_FRAGMENT_SAMPLERS,
   I965_DIRTY_VERTEX_SAMPLERS          = 1 << I965_STATE_VERTEX_SAMPLERS,
   I965_DIRTY_GEOMETRY_SAMPLERS        = 1 << I965_STATE_GEOMETRY_SAMPLERS,
   I965_DIRTY_COMPUTE_SAMPLERS         = 1 << I965_STATE_COMPUTE_SAMPLERS,
   I965_DIRTY_RASTERIZER               = 1 << I965_STATE_RASTERIZER,
   I965_DIRTY_DEPTH_STENCIL_ALPHA      = 1 << I965_STATE_DEPTH_STENCIL_ALPHA,
   I965_DIRTY_FS                       = 1 << I965_STATE_FS,
   I965_DIRTY_VS                       = 1 << I965_STATE_VS,
   I965_DIRTY_GS                       = 1 << I965_STATE_GS,
   I965_DIRTY_VERTEX_ELEMENTS          = 1 << I965_STATE_VERTEX_ELEMENTS,
   I965_DIRTY_BLEND_COLOR              = 1 << I965_STATE_BLEND_COLOR,
   I965_DIRTY_STENCIL_REF              = 1 << I965_STATE_STENCIL_REF,
   I965_DIRTY_SAMPLE_MASK              = 1 << I965_STATE_SAMPLE_MASK,
   I965_DIRTY_CLIP                     = 1 << I965_STATE_CLIP,
   I965_DIRTY_CONSTANT_BUFFER          = 1 << I965_STATE_CONSTANT_BUFFER,
   I965_DIRTY_FRAMEBUFFER              = 1 << I965_STATE_FRAMEBUFFER,
   I965_DIRTY_POLY_STIPPLE             = 1 << I965_STATE_POLY_STIPPLE,
   I965_DIRTY_SCISSOR                  = 1 << I965_STATE_SCISSOR,
   I965_DIRTY_VIEWPORT                 = 1 << I965_STATE_VIEWPORT,
   I965_DIRTY_FRAGMENT_SAMPLER_VIEWS   = 1 << I965_STATE_FRAGMENT_SAMPLER_VIEWS,
   I965_DIRTY_VERTEX_SAMPLER_VIEWS     = 1 << I965_STATE_VERTEX_SAMPLER_VIEWS,
   I965_DIRTY_GEOMETRY_SAMPLER_VIEWS   = 1 << I965_STATE_GEOMETRY_SAMPLER_VIEWS,
   I965_DIRTY_COMPUTE_SAMPLER_VIEWS    = 1 << I965_STATE_COMPUTE_SAMPLER_VIEWS,
   I965_DIRTY_SHADER_RESOURCES         = 1 << I965_STATE_SHADER_RESOURCES,
   I965_DIRTY_VERTEX_BUFFERS           = 1 << I965_STATE_VERTEX_BUFFERS,
   I965_DIRTY_INDEX_BUFFER             = 1 << I965_STATE_INDEX_BUFFER,
   I965_DIRTY_STREAM_OUTPUT_TARGETS    = 1 << I965_STATE_STREAM_OUTPUT_TARGETS,
   I965_DIRTY_COMPUTE                  = 1 << I965_STATE_COMPUTE,
   I965_DIRTY_COMPUTE_RESOURCES        = 1 << I965_STATE_COMPUTE_RESOURCES,
   I965_DIRTY_GLOBAL_BINDING           = 1 << I965_STATE_GLOBAL_BINDING,
   I965_DIRTY_ALL                      = 0xffffffff,
};

struct i965_context;

void
i965_init_state_functions(struct i965_context *i965);

void
i965_finalize_states(struct i965_context *i965);

#endif /* I965_STATE_H */
